version: 0.2

env:
  variables:
    TZ: "America/Sao_Paulo"
    buildFile: "aws/staging/build.xml"

phases:
  install:
    commands:
      - cp aws/staging/settings.xml ~/.m2/settings.xml
      - mvn dependency:get -DgroupId=ant-contrib -DartifactId=ant-contrib -Dversion=1.0b3
      - echo "Executando a acao de ${ACAO} para o projeto ${PROJETO}"
      - eval PASTAREAL=\$$ARTEFATO
      - echo $PASTAREAL
  pre_build:
    commands:
      - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime

  build:
    commands:
      - echo Build started
      - ant -f ${buildFile} do-magic

  post_build:
    commands:
      - echo Build completed