name: 99-Codebuild StartBuild

on:
  workflow_call:
    inputs:
      servidor:
        type: string
        required: false
      projeto:
        type: string
        required: true
      buildspec:
        type: string
        required: true
      nextVersion:
        type: string
        required: false
      majorVersion:
        type: string
        required: false
      thisVersion:
        type: string
        required: false
      versionLabel:
        type: string
        required: false
      gitdepth:
        type: string
        required: false
        default: 1
      branch:
        type: string
        required: false
    secrets:
      secretKey:
        required: true
      accessKey:
        required: true
      buildInfoToken:
        required: false
env:
  project-name: ${{ inputs.projeto }}
  buildspec-override: ${{ inputs.buildspec }}
  SERVER_TYPE: ${{ inputs.servidor }}
  NEXT_VERSION: ${{ inputs.nextVersion }}
  MAJOR_VERSION: ${{ inputs.majorVersion }}
  THIS_VERSION: ${{ inputs.thisVersion }}
  VERSION_LABEL: ${{ inputs.versionLabel }}
  git-depth: ${{ inputs.gitdepth }}
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  CodeBuild:
    runs-on: ubuntu-latest
    name: Job para iniciar um codebuild
    steps:
      - name: Configurando Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.accessKey}}
          aws-secret-access-key: ${{ secrets.secretKey }}
          aws-region: us-east-1
      - name: Obtendo variáveis para Override
        id: override-variables
        run: |
          echo override=$( node -e 'var options =[];
          function testAndPut(KEY) {
          if (process.env[KEY] !== undefined){
          options.push({"name": KEY, "value": process.env[KEY], "type": "PLAINTEXT"});}}
          testAndPut("SERVER_TYPE")
          testAndPut("VERSION_LABEL")
          testAndPut("THIS_VERSION")
          testAndPut("NEXT_VERSION")
          testAndPut("MAJOR_VERSION")
          testAndPut("BRANCH")
          console.log(JSON.stringify(options));' ) >> $GITHUB_OUTPUT
      - name: Iniciando o codebuild de fato
        id: start-build
        run: |
          aws codebuild start-build \
          --buildspec-override='${{env.buildspec-override}}' \
          --project-name=${{env.project-name}} \
          --source-version ${{ github.head_ref || github.ref_name }} \
          --git-clone-depth-override=${{env.git-depth}} \
          --output=text \
          --environment-variables-override '${{ steps.override-variables.outputs.override }}' > output.txt
          cat output.txt
          echo buildId=$( cat  output.txt | head -n 1 | cut -f 8 ) >> $GITHUB_OUTPUT
      - name: Enviando solicitação de registro de build
        id: send-build-data
        continue-on-error: true
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://build-info.hivecloud.com.br/build/start'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "x-auth-token": "${{ secrets.buildInfoToken }}"}'
          data: '{ "user": "${{ github.actor }}", "buildId": "${{ steps.start-build.outputs.buildId }}", "projectName": "${{ inputs.projeto }}", "branch": "${{ github.head_ref || github.ref_name }}", "serverType": "${{ inputs.servidor }}", "buildspec": "${{ inputs.buildspec }}" }'
      - name: Link na saída
        run: |
          echo '[Link para o codebuild](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/projects/${{env.project-name}}/build/${{ steps.start-build.outputs.buildId }})' >> $GITHUB_STEP_SUMMARY
          echo 'Variáveis passadas: ${{ steps.override-variables.outputs.override }}' >> $GITHUB_STEP_SUMMARY


