name: VERIFY / DEBUG / SNAPSHOT - Compila a aplicação, podendo ou não subir o servidor

on:
  workflow_call:
    inputs:
      servidor:
        type: string
        required: true
      projeto:
        type: string
        required: true
      snapshot:
        type: boolean
        required: true
env:
  project-name: ${{ inputs.projeto }}
  SERVER_TYPE: ${{ inputs.servidor }}
jobs:
  verify-Start-Codebuild:
    if: github.event.inputs.servidor != 'debug' && github.event.inputs.snapshot == 'false'
    uses: ./.github/workflows/codebuildStartBuild.yml@main
    with:
      projeto: ${{env.project-name}}
      buildspec: .aws/buildspec-compile-launch.yml
      servidor: ${{env.SERVER_TYPE}}
    secrets:
      secretKey: ${{ secrets.secretKey }}
      accessKey: ${{ secrets.accessKey}}

  debug-Start-Codebuild:
    if: github.event.inputs.servidor == 'debug' && github.event.inputs.snapshot == 'false'
    uses: ./.github/workflows/codebuildStartBuild.yml
    with:
      projeto: ${{env.project-name}}
      buildspec: .aws/buildspec-compile-debug.yml
      servidor: debug
    secrets:
      secretKey: ${{ secrets.secretKey }}
      accessKey: ${{ secrets.accessKey}}
  snapshot-Start-Codebuild:
    if: github.event.inputs.snapshot == 'true'
    uses: ./.github/workflows/codebuildStartBuild.yml
    with:
      projeto: ${{env.project-name}}
      buildspec: .aws/buildspec-snapshot.yml
      servidor: debug
    secrets:
      secretKey: ${{ secrets.secretKey }}
      accessKey: ${{ secrets.accessKey}}